# Theme Version | 当前版本
hjy: "1.0"

# >>> Basic Setup | 基础设置 <<<

# Header | 主菜单
## About Page: `hexo new page about`
## Tags Cloud Page: `hexo new page tags`
menu:
  首页: /
  文章归档: /archives/
  技能图谱: /skills/
  读书: /reading/
  关于我: /about/
  友情链接: /links/
  #RSS订阅: /atom.xml

# Subdirectory | 子目录
## If your site' url is 'http://yoursite.com/blog', set root_url as '/blog/'
## 网站若存放在子目录，请按上面格式填写
## https://hexo.io/docs/configuration.html#URL
root_url:

# Link to your avatar | 填写头像地址
avatar: /img/avatar.png

subnav:
  envelope: "mailto:haojunyu2012@gmail.com"
  Weibo: "sina weibo"
  GitHub: "https://github.com/haojunyu"
  #V2EX: "#"
  #RSS: "/atom.xml"
  #知乎: "zhihu"
  #豆瓣: "douban"
  #简书: "jianshu"
  #SegmentFault: ""
  #博客园: "http://www.cnblogs.com/happy-island/"
  #CSDN: "http://my.csdn.net/haojunyu2012"
  #网易云音乐: "netease"
  #虾米音乐: "xiami"
  #Facebook: "#"
  #Google: "#"
  #Twitter: "#"
  #LinkedIn: "#"
  #QQ: "#"
  #Wechat: "Wechat"
  #PayPal: "#"
  #StackOverflow: "#"
  #CodePen: ""
  #Plunker: ""
  #Instagram: "#"
  #Flickr: "#"
  #reddit: ""
  #Medium: ""
  #TiddlyWiki: ""
  #Tumblr: ""


# >>> Advantage Setup | 高级设置 <<<
# Featured Tags
featured-condition-size: 1     # 体现对该标签的熟悉程度


# >>> config

CDN:
  jquery: //cdn.bootcss.com/jquery/2.2.4/jquery.min.js
  bootstrap_css: //cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css
  bootstrap_js: //cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js
  bootstrap_theme: //cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"
  require: //cdn.bootcss.com/require.js/2.2.0/require.min.js
  fontawesome: //cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css
  fancybox_js: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
  fancybox_css: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
  animate_css: //cdn.bootcss.com/animate.css/3.5.1/animate.min.css
  jquery_ui_js: //cdn.bootcss.com/jqueryui/1.10.4/jquery-ui.min.js
  jquery_ui_css: //cdn.bootcss.com/jqueryui/1.10.4/css/jquery-ui.min.css
  pace_js: //cdn.bootcss.com/pace/1.0.2/pace.min.js
  clipboard: //cdn.bootcss.com/clipboard.js/1.5.10/clipboard.min.js
  mathjax: //cdn.bootcss.com/mathjax/2.6.1/MathJax.js
  scrollreveal: //cdn.bootcss.com/scrollReveal.js/3.1.4/scrollreveal.min.js
